# Generated by Django 4.2.16 on 2025-12-22 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('billed_units', models.PositiveIntegerField()),
                ('billing_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_reason', models.CharField(blank=True, choices=[('USER_RELEASE', 'User Release'), ('NODE_OFFLINE', 'Node Offline'), ('ADMIN_FORCE_RELEASE', 'Admin Force Release'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error')], max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=128)),
                ('response_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('lease_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('RELEASING', 'Releasing'), ('ENDED', 'Ended')], default='PENDING', max_length=16)),
                ('billing_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=16)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('billed_units', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('USER_RELEASE', 'User Release'), ('NODE_OFFLINE', 'Node Offline'), ('ADMIN_FORCE_RELEASE', 'Admin Force Release'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error')], max_length=32, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('device_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('device_secret_hash', models.CharField(blank=True, max_length=128)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('gpu_tier', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('FREE', 'Free'), ('ASSIGNED', 'Assigned'), ('IN_USE', 'In Use'), ('RELEASING', 'Releasing'), ('DISABLED', 'Disabled'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=16)),
                ('connection_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_version', models.CharField(blank=True, max_length=32, null=True)),
                ('capabilities', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('gpu_tier', models.CharField(max_length=64)),
                ('billing_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.AddConstraint(
            model_name='priceplan',
            constraint=models.UniqueConstraint(fields=('region', 'gpu_tier', 'billing_unit'), name='uniq_price_plan'),
        ),
        migrations.AddField(
            model_name='lease',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_plane.node'),
        ),
        migrations.AddField(
            model_name='lease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_plane.lease'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'scope', 'key'), name='uniq_idempotency_key'),
        ),
    ]
