# Generated by Django 4.2.16 on 2025-12-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
